version: "3.7"

services:
  odoo:
    restart: "no"
    environment:
      - DB_NAME_TEST=test_odoo
      - LOG_LEVEL=info
      - TEST_ENABLE=True
      - WITHOUT_DEMO=False
      - PIP_AUTO_INSTALL=1
      - DEBUGPY_ENABLE=0
    command: ["odoo"]
