version: "3.7"

volumes:
  odoo-data:
  postgres-odoo:

services:
  odoo:
    build: .
    env_file: .env
    
    restart: unless-stopped

    ports: ["8069:8069", "8072:8072", "41234:41234"]

    volumes:
      # Host paths (.ssh configuration)
      - ~/.ssh/:/opt/odoo/.ssh/:cached
      # Named volumes
      # TODO store files in database by default
      - odoo-data:${ODOO_DATA_DIR}
      # Development volumes
      - ./custom:${ODOO_EXTRA_ADDONS}:cached
    command: ["odoo", "--dev", "qweb,xml"]
    depends_on:
      - db

  db:
    image: postgres:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - postgres-odoo:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
