name: Run test

on:
  workflow_dispatch:
    inputs: {}

concurrency:
  # cancel already in progress jobs
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_run:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate config
      run: bash ./scripts/generate.sh compose

    - name: Build image
      run: docker-compose -f "docker-compose.yaml" build

    - name: Run test container
      run: docker-compose -f "docker-compose.yaml" -f "docker-compose.test.yaml" run odoo-test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
