name: Run test

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: Timeout in minutes
        default: "10"

jobs:
  test_run:
    timeout-minutes: ${{ fromJSON(inputs.timeout) }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build image
      run: docker-compose -f "docker-compose.yaml" build

    - name: Run test container
      run: docker-compose -f "docker-compose.yaml" -f "docker-compose.test.yaml" run odoo

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
